<?php

namespace Modules\Menu\Database\Seeders;

use Illuminate\Database\Seeder;

class MenuDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         $data = [
            [
                'parent_menu_id' => 0,
                'mtype' => 'main',
                'mlevel' => 'Parent',
                'web_title' => 'Dashboard',
                'app_title' => 'Dashboard',
                'web_link' => '/',
                'app_link' => '/',
                'sort_order' => 1,
                'web_filter' => 0,
                'app_filter' => 0,
                'web_icon' => 'hi2:HiSquares2X2',
                'app_icon' => 'hi2:HiSquares2X2',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
            ],
            [
                'parent_menu_id' => 0,
                'mtype' => 'main',
                'mlevel' => 'Parent',
                'web_title' => 'Prospects',
                'app_title' => 'Prospects',
                'web_link' => '/prospects?view=list',
                'app_link' => '/prospects?view=list',
                'sort_order' => 2,
                'web_filter' => 0,
                'app_filter' => 0,
                'web_icon' => 'hi:HiUserGroup',
                'app_icon' => 'hi:HiUserGroup',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
            ],
            [
                'parent_menu_id' => 0,
                'mtype' => 'main',
                'mlevel' => 'Parent',
                'web_title' => 'Students',
                'app_title' => 'Students',
                'web_link' => '/students?view=list',
                'app_link' => '/students?view=list',
                'sort_order' => 3,
                'web_filter' => 0,
                'app_filter' => 0,
                'web_icon' => 'hi:HiAcademicCap',
                'app_icon' => 'hi:HiAcademicCap',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
            ],
            [
                'parent_menu_id' => 0,
                'mtype' => 'main',
                'mlevel' => 'Parent',
                'web_title' => 'Families',
                'app_title' => 'Families',
                'web_link' => '/families?view=list',
                'app_link' => '/families?view=list',
                'sort_order' => 4,
                'web_filter' => 0,
                'app_filter' => 0,
                'web_icon' => 'hi:HiUserGroup',
                'app_icon' => 'hi:HiUserGroup',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
            ],
            [
                'parent_menu_id' => 0,
                'mtype' => 'main',
                'mlevel' => 'Parent',
                'web_title' => 'Team',
                'app_title' => 'Team',
                'web_link' => '/team?view=list',
                'app_link' => '/team?view=list',
                'sort_order' => 5,
                'web_filter' => 0,
                'app_filter' => 0,
                'web_icon' => 'hi:HiUsers',
                'app_icon' => 'hi:HiUsers',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
            ],
            [
                'parent_menu_id' => 0,
                'mtype' => 'main',
                'mlevel' => 'Parent',
                'web_title' => 'Calendar',
                'app_title' => 'Calendar',
                'web_link' => '/calendar',
                'app_link' => '/calendar',
                'sort_order' => 6,
                'web_filter' => 0,
                'app_filter' => 0,
                'web_icon' => 'hi2:HiCalendarDays',
                'app_icon' => 'hi2:HiCalendarDays',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
            ],
            [
                'parent_menu_id' => 11,
                'mtype' => 'sub-main',
                'mlevel' => 'Child',
                'web_title' => 'Payroll',
                'app_title' => 'Payroll',
                'web_link' => '/payroll/summary',
                'app_link' => '/payroll/summary',
                'sort_order' => 11.2,
                'web_filter' => 0,
                'app_filter' => 0,
                'web_icon' => 'hi:HiCurrencyDollar',
                'app_icon' => 'hi:HiCurrencyDollar',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
            ],
            [
                'parent_menu_id' => 0,
                'mtype' => 'main',
                'mlevel' => 'Parent',
                'web_title' => 'Resources',
                'app_title' => 'Resources',
                'web_link' => '',
                'app_link' => '',
                'sort_order' => 8,
                'web_filter' => 0,
                'app_filter' => 0,
                'web_icon' => 'hi2:HiComputerDesktop',
                'app_icon' => 'hi2:HiComputerDesktop',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
            ],
            [
                'parent_menu_id' => 0,
                'mtype' => 'main',
                'mlevel' => 'Parent',
                'web_title' => 'Integrations',
                'app_title' => 'Integrations',
                'web_link' => '/integration',
                'app_link' => '/integration',
                'sort_order' => 9,
                'web_filter' => 0,
                'app_filter' => 0,
                'web_icon' => 'hi:HiPuzzle',
                'app_icon' => 'hi:HiPuzzle',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
            ],
            [
                'parent_menu_id' => 11,
                'mtype' => 'sub-main',
                'mlevel' => 'Child',
                'web_title' => 'Invoices & Billing',
                'app_title' => 'Invoices & Billing',
                'web_link' => '/invoices/summary',
                'app_link' => '/invoices/summary',
                'sort_order' => 11.3,
                'web_filter' => 0,
                'app_filter' => 0,
                'web_icon' => 'hi2:HiBanknotes',
                'app_icon' => 'hi2:HiBanknotes',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
            ],
            [
                'parent_menu_id' => 0,
                'mtype' => 'main',
                'mlevel' => 'Parent',
                'web_title' => 'Reports',
                'app_title' => 'Reports',
                'web_link' => '',
                'app_link' => '',
                'sort_order' => 11,
                'web_filter' => 0,
                'app_filter' => 0,
                'web_icon' => 'hi:HiChartPie',
                'app_icon' => 'hi:HiChartPie',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
            ],
            
            [
                'parent_menu_id' => 11,
                'mtype' => 'sub-menu',
                'mlevel' => 'Child',
                'web_title' => 'Attendance',
                'app_title' => 'Attendance',
                'web_link' => '/attendance',
                'app_link' => '/attendance',
                'sort_order' => 11.01,
                'web_filter' => 0,
                'app_filter' => 0,
                'web_icon' => 'hi:HiUserGroup',
                'app_icon' => 'hi:HiUserGroup',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
            ],
            [
                'parent_menu_id' => 0,
                'mtype' => 'main',
                'mlevel' => 'Parent',
                'web_title' => 'Security',
                'app_title' => 'Security',
                'web_link' => '',
                'app_link' => '',
                'sort_order' => 12,
                'web_filter' => 0,
                'app_filter' => 0,
                'web_icon' => 'hi2:HiMiniFingerPrint',
                'app_icon' => 'hi2:HiMiniFingerPrint',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
            ],
            [
                'parent_menu_id' => 13,
                'mtype' => 'sub-menu',
                'mlevel' => 'Child',
                'web_title' => 'Login Activity',
                'app_title' => 'Login Activity',
                'web_link' => '/login-activity',
                'app_link' => '/login-activity',
                'sort_order' => 13.01,
                'web_filter' => 0,
                'app_filter' => 0,
                'web_icon' => 'hi:HiUserGroup',
                'app_icon' => 'hi:HiUserGroup',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
            ],
        ];
        DB::table('menus')->insert($data);
    }
}
