<?php

namespace Modules\Permission\Database\Seeders;

use Illuminate\Database\Seeder;

class PermissionDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'role_id' => 1,
                'menu_id' => 1,
                'allow_create' => 1,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 1,
            ],
[
                'role_id' => 1,
                'menu_id' => 2,
                'allow_create' => 1,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 1,
            ],

            [
                'role_id' => 1,
                'menu_id' => 3,
                'allow_create' => 1,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 1,
            ],
            [
                'role_id' => 1,
                'menu_id' => 4,
                'allow_create' => 1,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 0,
            ],
            [
                'role_id' => 1,
                'menu_id' => 5,
                'allow_create' => 1,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 1,
            ],
            [
                'role_id' => 1,
                'menu_id' => 6,
                'allow_create' => 1,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 1,
            ],
            [
                'role_id' => 1,
                'menu_id' => 7,
                'allow_create' => 1,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 1,
            ],
            [
                'role_id' => 1,
                'menu_id' => 8,
                'allow_create' => 0,
                'allow_read' => 0,
                'allow_update' => 0,
                'allow_delete' => 0,
            ],
            [
                'role_id' => 1,
                'menu_id' => 9,
                'allow_create' => 1,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 1,
            ],
            [
                'role_id' => 1,
                'menu_id' => 10,
                'allow_create' => 1,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 1,
            ],
            [
                'role_id' => 1,
                'menu_id' => 11,
                'allow_create' => 1,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 1,
            ],       
            [
                'role_id' => 1,
                'menu_id' => 12,
                'allow_create' => 1,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 1,
            ],
            [
                'role_id' => 1,
                'menu_id' => 13,
                'allow_create' => 1,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 1,
            ],
            [
                'role_id' => 1,
                'menu_id' => 14,
                'allow_create' => 1,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 1,
            ],
            // ...additional seed tutor...
            [
                'role_id' => 2,
                'menu_id' => 1,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 0,
                'allow_delete' => 0,
            ],
            [
                'role_id' => 2,
                'menu_id' => 3,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 0,
                'allow_delete' => 0,
            ],
            [
                'role_id' => 2,
                'menu_id' => 4,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 0,
                'allow_delete' => 0,
            ],
            [
                'role_id' => 2,
                'menu_id' => 5,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 0,
                'allow_delete' => 0,
            ],
            [
                'role_id' => 2,
                'menu_id' => 6,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 0,
            ],
            [
                'role_id' => 2,
                'menu_id' => 8,
                'allow_create' => 0,
                'allow_read' => 0,
                'allow_update' => 0,
                'allow_delete' => 0,
            ],
          
            // ...additional seed Staff...
             [
                'role_id' => 3,
                'menu_id' => 1,
                'allow_create' => 1,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 0,
            ],
            [
                'role_id' => 3,
                'menu_id' => 5,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 0,
            ],
             [
                'role_id' => 3,
                'menu_id' => 6,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 0,
            ],
            [
                'role_id' => 3,
                'menu_id' => 7,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 0,
            ],
             [
                'role_id' => 3,
                'menu_id' => 8,
                'allow_create' => 0,
                'allow_read' => 0,
                'allow_update' => 0,
                'allow_delete' => 0,
            ],
            [
                'role_id' => 3,
                'menu_id' => 9,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 0,
            ],
             [
                'role_id' => 3,
                'menu_id' => 10,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 0,
            ],
            [
                'role_id' => 3,
                'menu_id' => 11,
                'allow_create' => 1,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 0,
            ],
             // ...additional seed Family...
             [
                'role_id' => 4,
                'menu_id' => 1,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 0,
            ],
            [
                'role_id' => 4,
                'menu_id' => 4,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 0,
                'allow_delete' => 0,
            ],
             [
                'role_id' => 4,
                'menu_id' => 6,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 0,
                'allow_delete' => 0,
            ],
           // ...additional seed Student...
             [
                'role_id' => 5,
                'menu_id' => 1,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 1,
                'allow_delete' => 0,
            ],
            [
                'role_id' => 5,
                'menu_id' => 3,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 0,
                'allow_delete' => 0,
            ],
             [
                'role_id' => 5,
                'menu_id' => 6,
                'allow_create' => 0,
                'allow_read' => 1,
                'allow_update' => 0,
                'allow_delete' => 0,
            ], 
[
                'role_id' => 5,
                'menu_id' => 8,
                'allow_create' => 0,
                'allow_read' => 0,
                'allow_update' => 0,
                'allow_delete' => 0,
            ], 

        ];
        DB::table('permissions')->insert($data);
    }
}
